### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by rahulkore** [AshokPrjapati/Meesho-clone#51]
# Review Comments
- UI Aspects
  - Pros
    - UI looks descent 
    - many number of components are present.
    - Functionality wise , it is rich in functionalities.
    - wireframing looks good.
    - Redux arch is used correctly.
    
  - Cons
     - Localization is not done correctly
	 - Not able to signup, wasn't able to get the otp.
     - Some links are broken . 
     - Not much comments are present in code.
	 - Able to add item to cart, without logging in
  
 
  

- Overall Comments 
  - Little more focus on back end could have been great .
  - some of the components from UI could have been reduced and that much effort could have been given to back end side development .
  - coding standard , functionality all are maintained at a good quality .
  - use of git is done very good , design patterns are good .
  - no of components could've been reduced and those efforts could've been utilized on making the components working .
  - Next time focus on workable features rather than more no of features . 
  - Don't keep any commented code.

**Comment by AshokPrjapati** [comment]
done
